### ISSUE TITLE
"Note" markdown should include `class="note"` in the resulting `<div>`

### ISSUE THREAD

**Issue by rcritz** [BlackDragonBE/MarkdownToRW_Converter#1]
The converter correctly puts a markdown "Note" into a separate `<div>` tag. It should include the attribute `class="note"` on that `<div>` to match styling on the site.

**Comment by BlackDragonBE** [comment]
@rcritz 
Hey RIchard, can you post the original markdown and the html result you got?
This is how the app converts notes: 

![image](https://user-images.githubusercontent.com/8495163/37560619-49ca7fbc-2a3c-11e8-9bf3-13925168e58b.png)

Cheers!

**Comment by rcritz** [comment]
![screen shot 2018-03-17 at 6 40 22 pm](https://user-images.githubusercontent.com/3411176/37560640-b26e36dc-2a12-11e8-87ca-9e2de555c29f.png)


Here ya go, Eric!

**Comment by rcritz** [comment]
I'm happy to send you the markdown file if you want it.

**Comment by BlackDragonBE** [comment]
Sure, that would be even better!
I'll look into this, I'm not sure why it's parsing that incorrectly.

**Comment by BlackDragonBE** [comment]
Fixed with d0cbc73d5 which will be included in the next release.
