### ISSUE TITLE
error message in terminal on launch (for GUI version, MacOS)

### ISSUE THREAD

**Issue by abunur** [BlackDragonBE/MarkdownToRW_Converter#5]
on launch, the following error appears in terminal:
objc[12285]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fffac3f2210) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x1128d0dc8). One of the two will be used. Which one is undefined.

**Comment by BlackDragonBE** [comment]
@abunur That error/warning is harmless. Lots of applications cause that because the same class is defined in multiple modules. It's an Apple issue, but it won't (or shouldn't) cause any trouble.

In this case, it's the file open dialog that's defined in both FinderKit & FileProvider.
